### ISSUE TITLE
[SUGESTÃO] ADICIONAR A CONVENÇÃO DE COMMIT NO GUIA DE CONTRIBUIÇÃO

### ISSUE THREAD

**Issue by ghost** [digitalinnovationone/dio-lab-open-source#15962]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema.
NÃO

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você quer que aconteça.
Adicionar informações referentes a padronização das mensagens

**Descreva as alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.

**Contexto adicional**
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.
N/A

**Comment by NogueiraBrenda** [comment]
Obrigado
