### ISSUE TITLE
[BUG] CORRIGIR "CONTRIBUTING.md e ISSUE fixada

### ISSUE THREAD

**Issue by samaraturchetto** [digitalinnovationone/dio-lab-open-source#19897]
**Descreva o bug**

O item "3" das instruções do [Guia de Contribuição](https://github.com/digitalinnovationone/dio-lab-open-source/blob/main/CONTRIBUTING.md) (e na [ISSUE](https://digitalinnovationone.github.io/dio-lab-open-source/) fixada no about ao lado direito) está descrito da seguinte maneira:  
"3. Adicione o remote upstream para manter seu repositório local atualizado: git remote add upstream https://github.com/_**elidianaandrade**_/dio-lab-open-source.git;"

O que acaba levando o aluno ao erro na hora de adicionar a upstream de um repo errado do que é atualmente, já que o correto é:

"https://github.com/digitalinnovationone/dio-lab-open-source.git"

(No [README](https://github.com/digitalinnovationone/dio-lab-open-source/blob/main/README.md) do repo principal da dio está correto. 

Mas como tem "LEIA A ISSUE FIXADA!" destacado no about ao lado, pode levar ao aluno abrir o link e seguir as instruções por ali. (Aconteceu comigo, não tava conseguindo fazer o projeto, porque na aula gravada também usa o link dela, acabei copiando e colando da issue e deu tudo errado kkkk até que eu descobri que era isso).

**Comment by GustavoPereira-Dev** [comment]
Corrigi esse erro agora à pouco
