### ISSUE TITLE
[BUG] Erro no link do Getting Started with Git and GitHub

### ISSUE THREAD

**Issue by cyhvar** [digitalinnovationone/dio-lab-open-source#22902]
**Descreva o bug**
Ao clicar no link leva a uma página de erro.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para dio-lab-open-source 
2.  Role para baixo até as instruções para realizar o desafio na opção veja mais do item 3
3. Clicar no link "Getting Started with Git and GitHub"
4. Erro 404 - This is not the web page you are  

**Comportamento esperado**
Era esperado que abrisse os materiais de apoio.

**Contexto adicional**
Possivelmente não existe mais .

**Comment by GustavoPereira-Dev** [comment]
Pelo que cheguei a ver, o problema é que o tal repositório (digitalinnovationone/dio-curso-git-github) por algum motivo é inexistente
Ou seja, foi removido por algum motivo e não removeram/trocaram para outro link isso
A solução seria trocar o endereço url para um outro interno desse repo mesmo, como redirecionado para o ROADMAP_GITHUB.md, ou para algum tutorial do docs.github
