### ISSUE TITLE
[SUGESTÃO] Adicionar a convenção de commits no Guia de Contribuição

### ISSUE THREAD

**Issue by biamotaz** [digitalinnovationone/dio-lab-open-source#23218]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização das mensagens  dos commits no [Guia de Contribuição](https://github.com/digitalinnovationone/dio-lab-open-source/blob/d2c8756e68e04b21826b658641c2f7f36e4a4235/CONTRIBUTING.md).

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos de commits e uma descrição a respeito do seu uso.

**Contexto adicional**
N/A

**Comment by tiocostela** [comment]
Obrigado pela colaboração, é uma boa sugestão. Vou adicioná-la ao Guia.
