### ISSUE TITLE
[BUG] Não consigo clonar o repositório na minha máquina

### ISSUE THREAD

**Issue by kaique-feitosa** [digitalinnovationone/dio-lab-open-source#26890]
**Descreva o bug**
Depois que faço o fork do projeto e vou usar o comando git clone aparece essa mensagem de erro

error: 7054 bytes of body are still expected7 MiB | 461.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Reproduzir**

**Comportamento esperado**
Baixar todos os arquivos do repositório localmente

**Capturas de tela**
![Captura de tela 2024-04-15 202715](https://github.com/digitalinnovationone/dio-lab-open-source/assets/147649641/59a8ad0f-2d3e-46f9-af9d-875981b7dbc9)

**Desktop (preencha as seguintes informações):**
  - SO: Windows
  - Navegador: Chrome
  - Versão: 11

**Smartphone (preencha as seguintes informações):**
 N/A

**Contexto adicional**
N/A

**Comment by Christian-Zafalon** [comment]
Outro ponto é o OneDrive, ja vi casos que o git não se comporta como deveria em uma pasta OneDrive

**Comment by kaique-feitosa** [comment]
Já consegui resolver rsrs obrigado pela ajuda!
