### ISSUE TITLE
[SUGESTÃO] Adicionar a explicação do uso do GitHub Desktop.

### ISSUE THREAD

**Issue by Rafael-Dutra-create** [digitalinnovationone/dio-lab-open-source#277]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar a explicação do uso do GitHub Desktop.

**Descreva as alternativas que você considerou**
Inserir uma explicação de como usar o GitHub Desktop para fazer contribuições em projetos open sourcer e a explicação de como utiliza-lo para futuros projetos.

**Contexto adicional**
N/a

**Comment by elidianaandrade** [comment]
Olá! Nos Bootcamps os conteúdos são mais intensivos, mas na [Formação GitHub Certification](https://web.dio.me/track/formacao-github-certification), a Aline (@alinealien)  aborda sobre o GitHub Desktop 😊
