### ISSUE TITLE
[Comentários]  Adicionar uma aba para comentários entre a comunidade, para troca de informações e conteúdos. 

### ISSUE THREAD

**Issue by TauanTeles** [digitalinnovationone/dio-lab-open-source#28598]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Troca de informação entre os usuários 

**Descreva as alternativas que você considerou**
Inserir um local para troca de informações e conteúdos 

**Contexto adicional**
NA

**Comment by TauanTeles** [comment]
Apenas um teste para o bootcamp.

**Comment by elidianaandrade** [comment]
Olá, @TauanTeles! A aba de "[Discussões](https://github.com/digitalinnovationone/dio-lab-open-source/discussions)" está habilitada neste repositório. Saiba mais em: [https://github.com/digitalinnovationone/dio-lab-open-source/discussions/30390](https://github.com/digitalinnovationone/dio-lab-open-source/discussions/30390) 😊
