### ISSUE TITLE
[BUG] Aula: Desenvolvendo uma Contribuição

### ISSUE THREAD

**Issue by pedrogouveadoamaral** [digitalinnovationone/dio-lab-open-source#29325]
**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
No minuto 09:56 do vídeo Contribuindo em um Projeto Open Source no GitHub foi demonstrado que para criar o arquivo .md dentro da pasta community, era pra executar o comando touch community usuario.md. Mas o arquivo foi criado dentro da pasta raiz do projeto.

**Comportamento esperado**
De acordo com a explicação do vídeo, ao usar o comando touch community usuario.md, o esperado era que o arquivo usuario.md fosse criado dentro da pasta community. Mas no meu ambiente isso e de mais alguns usuários que estão com o arquivo criado na pasta raíz, o esperado não ocorreu.
Para que eu pudesse criar o arquivo pelo git bash corretamente, utilizei duas estratégias distintas, sendo:
1 - Naveguei para dentro da pasta community usando dir community e usei o comando  touch pedrogouveadoamaral.md
2 - utilizei o comando touch community/pedrogouveadoamaral.md

**Capturas de tela**
![image](https://github.com/digitalinnovationone/dio-lab-open-source/assets/65814729/12a8d628-d674-4713-af28-fd8bd538dda7)
No print acima, podemos perceber que existem alguns arquivos .md de usuários criados dentro da pasta raiz. Acredito que eles só seguiram o que foi orientado no vídeo e não se atentaram de que o arquivo não foi devidamente criado na pasta pretendida.

**Comment by elidianaandrade** [comment]
Olá, Pedro! Tudo bem? No vídeo, é usado o comando `touch community/username.md`, e não  `touch community username.md` como citou. Inclusive, posteriormente, demonstro que o arquivo foi criado na pasta community.
![Aula Desenvolvendo uma Contribuição](https://github.com/digitalinnovationone/dio-lab-open-source/assets/97471199/d39897e6-34ec-4fd6-a098-ef65c2a6786d)

Sobre os arquivos na pasta incorreta, eles já foram corrigidos e a automação atualizada 😊

**Comment by pedrogouveadoamaral** [comment]
Obrigado pela resposta, Elidiana.
Antes de mais nada, peço desculpas pela issue criada. 
Revi o trecho do vídeo, e sinceramente não sei como eu não enxergei a / no comando. Novamente, desculpe-me.
Parabéns pelo trabalho com o material sobre o Git/GitHub. Eu já utilizava o Github em projetos pessoais, e cheguei a fazer um PR em um repositório de um amigo, mesmo assim aprendi várias coisas que você demonstrou.

**Comment by elidianaandrade** [comment]
Por nada, Pedro! Tranquilo! O importante é que a sua intenção foi ajudar e você foi respeitoso 😊
