### ISSUE TITLE
[SUGESTÃO]

### ISSUE THREAD

**Issue by khalil1187** [digitalinnovationone/dio-lab-open-source#30666]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Minha sugestão é sobre uso alternativo do Git-Bash

**Descreva a solução que você gostaria**
Uso de Git&Git-Hub através do Git-Hub Desktop

**Descreva as alternativas que você considerou**
Uso do VScode e do aplicativo Git-Hub desktop

**Contexto adicional**
Creio que a maioria de pessoas que estão iniciando agora encontram dificuldades em utilizar o Git-Bash.
pois uma grande parte é iniciante e encontrou dificuldades ou esta pedindo por mais conteúdo.
através das aulas eu pude conhecer mais sobre, uma pesquisa a fundo encontrei a forma de usar o recurso através do aplicativo Git-Hub Desktop a qual associado ao Git ficou fácil de manuesar o projeto e estar salvando ou alterando tal, de forma intuitiva e ilustrativa.
Desta forma creio que mais pessoas estarão disposto a conhecer mais sobre esta plataforma.

![Git-Hub desktop](https://github.com/digitalinnovationone/dio-lab-open-source/assets/168208993/9de05473-1d80-4a74-b852-f755feeeb07f)

**Comment by elidianaandrade** [comment]
Olá! Nos Bootcamps os conteúdos são mais intensivos, mas na [Formação GitHub Certification](https://web.dio.me/track/formacao-github-certification), a Aline (@alinealien)  aborda sobre o GitHub Desktop 😊
