### ISSUE TITLE
[SUGESTÃO] Atualização do conteudo das aulas relacionadas ao GitHub

### ISSUE THREAD

**Issue by Brudesa** [digitalinnovationone/dio-lab-open-source#30763]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Atualização do conteudo das aulas relacionadas ao GitHub

**Descreva a solução que você gostaria**
Gostaria que o modulo de git hub fosse atualizado com as funcionalidades do GitHub Desktop

**Descreva as alternativas que você considerou**
A utilização do programa GitHub Desktop, seria interessante.

**Contexto adicional**
N/A

**Comment by elidianaandrade** [comment]
Olá! Nos Bootcamps os conteúdos são mais intensivos, mas na [Formação GitHub Certification](https://web.dio.me/track/formacao-github-certification), a Aline (@alinealien)  aborda sobre o GitHub Desktop 😊
