### ISSUE TITLE
[SUGESTÃO] Sugestão de Alteração de Repositório

### ISSUE THREAD

**Issue by TiagoOGarcia** [digitalinnovationone/dio-lab-open-source#31648]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Sinalizar que houve alteração no local sinalizado na aula relacionada ao Projeto Open Sourse, pois na aula sinaliza que está com o usuário Elidianaandrade, mas na realidade hoje está na Digitalinnovation. Fiquei um pouco confuso para entender na hora.

**Descreva as alternativas que você considerou**
Inserir uma mensagem sinalizando um update relacionada a essa alteração.

**Contexto adicional**
N/A.

**Comment by elidianaandrade** [comment]
Olá, @TiagoOGarcia! Tudo bem? Essa sinalização está feita em "**Entendendo o Desafio**", e ao tentar acessar [https://github.com/elidianaandrade/dio-lab-open-source/](https://github.com/digitalinnovationone/dio-lab-open-source/) você é redirecionado ao repositório da [digitalinnovationone](https://github.com/digitalinnovationone/dio-lab-open-source/). Na aula de resumo feita pelo Venilton ele apresenta já neste repositório 😊
