### ISSUE TITLE
[SUGESTÃO] Adionar a convenção de commits no guia de contribuição

### ISSUE THREAD

**Issue by renatobras** [digitalinnovationone/dio-lab-open-source#35875]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar informações referentes a pradonização de commits no [Guia de contribuição](https://github.com/renatobras/dio-lab-open-source-copy/blob/main/CONTRIBUTING.md).

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando oss tipos de commits e uma descrição do seu uso.

**Contexto adicional**
N/A.

**Comment by Danilo019** [comment]
É boa sugestão! Eu irei está adicionando.
