### ISSUE TITLE
[SUGESTÃO] Adicionar a convenção de commits no Guia de Contribuição (3ª tentativa)

### ISSUE THREAD

**Issue by PCVCPAULO** [digitalinnovationone/dio-lab-open-source#38448]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não sei como, mas ao executar o "git add" com a minha contribuição, foi incluído um segundo arquivo "000tauan.md", que estava com o status deleted, ou seja havia sido excluído do repositório "community". Ocasionando erro na minha contribuição. 

**Descreva a solução que você gostaria**
Que mantivesse no arquivo "CONTRIBUTING.md" e no arquivo "README.md" , do repositório "dio-lab-open-source, as orientações originais disponibilizadas pela Expert Elidiana Andrade, uma vez que houve alterações o conteúdo do Github está diferente do que é apresentado na vídeo aula.

**Descreva as alternativas que você considerou**
Tive que excluir do repositório community, tudo que havia feito durante a aula.

**Contexto adicional**
Erro causado.
![Fluxo_Trabalho_Erro](https://github.com/digitalinnovationone/dio-lab-open-source/assets/37885954/d937af2b-5a5f-4a15-b2fa-65e8b2796ba4)

**Comment by elidianaandrade** [comment]
https://github.com/digitalinnovationone/dio-lab-open-source/discussions/28015#discussioncomment-9703479
