### ISSUE TITLE
[SUGESTÃO] Adicionar a convenção de commits no Guia de Comtribuição

### ISSUE THREAD

**Issue by tiburciobh** [digitalinnovationone/dio-lab-open-source#39518]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização das mensagens de commits no guia de contribuição

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos e commits e uma descrição a respeito do seu uso

**Contexto adicional**
N/A

**Comment by FranklimMendes** [comment]
Boa sugestão!
