### ISSUE TITLE
[SUGESTÃO] Adicionar convenção de commits no Guia de Contribuição

### ISSUE THREAD

**Issue by ka-souzacp** [digitalinnovationone/dio-lab-open-source#41558]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
N/A

**Descreva a solução que você gostaria**
N/A

**Descreva as alternativas que você considerou**
N/A

**Contexto adicional**
N/A

**Comment by eknerph** [comment]
Obrigado pela colaboração! É uma boa sugestão. vou adiciona-la ao Guia.

**Comment by DaniCrisCastro** [comment]
BOA
