### ISSUE TITLE
[SUGESTÃO] Tem uma explicação mais concisa

### ISSUE THREAD

**Issue by gevessons** [digitalinnovationone/dio-lab-open-source#50871]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Ela começa explicando e entrado em vários tópicos sem finalizar algumas explicações de como deve proceder.

**Descreva a solução que você gostaria**
Terminar de explicar um assunto que começa, sem iniciar um novo tema no meio da explicação, deixando a pessoa perdida.

**Comment by gevessons** [comment]
Finalizando a contribuição

**Comment by guimatth** [comment]
boa
