### ISSUE TITLE
[SUGESTÃO] Commits no Guia de Contribuição

### ISSUE THREAD

**Issue by pereirarob** [digitalinnovationone/dio-lab-open-source#555]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Informações importantes à padronização das mensagens dos commits na Guia de Contribuição

**Descreva as alternativas que você considerou**
Considerei a inserção das tabelas, demonstrando os tipos de commits e uma descrição a respeito do seu uso.

**Contexto adicional**
N/A

**Comment by pereirarob** [comment]
Leia a documentação.

**Comment by vitoriaft** [comment]
Obrigada pela contribuição!
