### ISSUE TITLE
FAQ: Sobre a Publicação do Desafio na Plataforma e a Solicitação de Pull Request

### ISSUE THREAD

**Issue by elidianaandrade** [digitalinnovationone/dio-lab-open-source#5587]
Olá, pessoal! Espero que estejam bem! Antes de tudo gostaria de agradecer o feedback de vocês e peço desculpas, pois ainda não consegui responder a todos, mas estou passando aqui rapidinho para esclarecer algumas dúvidas sobre o envio do desafio na plataforma.

**1. Só posso entregar o Desafio na Plataforma depois que o meu Pull Request for aceito?**
Não, pois o repositório que será enviado é o seu, exemplo `https://github.com/SEUUSERNAMEDOGITHUB/dio-lab-open-source/`. 
![image](https://github.com/elidianaandrade/dio-lab-open-source/assets/97471199/385192d2-717a-40ee-bf77-d57e00a7a756)
Após o envio ele fica exibido no seu perfil da DIO basta acessar `https://web.dio.me/users/SEUUSUARONADIO?tab=projects&page=1`, substituindo `SEUUSUARIONADIO` pelo seu nome de usuário na plataforma:

![image](https://github.com/elidianaandrade/dio-lab-open-source/assets/97471199/168df715-051c-48c2-83c4-4f7ec196601d)
```
https://web.dio.me/users/SEUUSUARONADIO?tab=projects&page=1
```

Tendo em vista que você criou o commit no seu repositório, ele estará presente lá independentemente de aceitar ou não o Pull Request. Ao aceitar o que acontece é que o seu commit passa a fazer parte desse repositório também.

**2. Quando meu Pull Request será aceito?**
Como comentei em outra Issue sobre a manutenção do repositório,  já comuniquei a DIO para indicar um moderador. Eu não tenho vínculo empregatício com a plataforma e também atuo como freelance em outra empresa, então no meu tempo livre dou manutenção aqui de maneira voluntária.

**Nota:** Escrevi aqui rapidinho caso mais alguém tenha alguma dúvida, assim que eu puder atualizo / corrijo algo que não tenha ficado claro.

**Comment by thiagolosalmeidas** [comment]
Precisa de uma força tarefa para fazer a revisão. :)

**Comment by thayana2021js** [comment]
muito bom essa tarefa

**Comment by pedroribeirocosta** [comment]
Ótimas informações!

**Comment by AllanCastroLeao** [comment]
professora! preciso de ajuda! sempre que tento clonar no bash o repositório aparece essa mensagem: remote: Repository not found.
fatal: repository 'https://github.com/clone/dio-lab-open-source.git/' not found

já pesquisei porem não consigo solucionar o problema...

**Comment by thejappa89** [comment]
O repositório citado realmente não existe. https://github.com/**CLONE**/dio-lab-open-source.git/

Repositório digitado com erro: ttps://github.com/**CLONE**/dio-lab-open-source.git/
Repositório correto: https://github.com/**elidianaandrade**/dio-lab-open-source.git/

**Comment by JoAmaralRocha** [comment]
Não consigo mesclar meu desafio, não aparece pra mim a opção de mesclar

**Comment by falvojr** [comment]
Fala galera, tudo beleza!? Venilton da DIO aqui 😊
@elidianaandrade muito obrigado por esse Desafio de Projeto incrível, ele realmente alcançou um número impressionante de pessoas 🚀 Muito obrigado pelo trabalho incrível, você é demais 👊🤩
Nesse sentido, vamos trabalhar juntos na criação de uma automação que irá validar os PRs em relação às instruções definidas no `README.md` e `CONTRIBUTE.md`. Isso já está funcionando para novos PRs, mas ainda vamos evoluir para que todos os mais de 10k sejam avaliados, aprovados e mergeados em breve. Por isso, adicionei a label de melhoria nesta Issue, assim todos podem acompanhar esta importante evolução 🫶

**Comment by brunop27** [comment]
Bom dia. Fiz uma pull request a duas semanas quando comecei o curso com a Eli, ela serve pra enviar uma colaboração né? ("Se entendi bem"), mas vi muitos sendo aprovados, mas não encontro a minha na pasta community. Como posso saber se fiz certo, se foi aceita ou se preciso refazela?

**Comment by F-Shouter** [comment]
Força que vocês conseguem! 😂😊👍👍

**Comment by falvojr** [comment]
Oi pessoal👋,

Trago boas notícias! Concluímos o workflow que automatiza a aprovação e merge de PRs relacionados ao Desafio de Projeto (Lab) da DIO 🎉🎉🎉. Para quem quiser conferir, ele está disponível neste repositório em [.github/workflows/dio-lab-validate-and-merge.yml](https://github.com/digitalinnovationone/dio-lab-open-source/blob/main/.github/workflows/dio-lab-validate-and-merge.yml).

O que fizemos foi validar se o autor do PR está adicionando ou modificando apenas o seu arquivo de perfil, seguindo o padrão `community/SEU_USERNAME.md` (como `community/falvojr.md` no meu caso). Graças a isso, conseguimos mergear quase 6 mil PRs neste último fim de semana 🤩. Para alcançar essa façanha, criamos um script em Python que adicionou a label `run dio workflow` em todos os PRs abertos. Fizemos isso porque, originalmente, nosso workflow era acionado apenas ao abrir ou atualizar um PR. No entanto, configuramos temporariamente para ser ativado com a inclusão desta label.

Graças a esta automatização, encerramos a maioria dos PRs abertos. No entanto, alguns ainda estão pendentes, pois não cumpriram as regras de validação do nosso Workflow (que é conter apenas o arquivo `community/SEU_USERNAME.md`). Por isso, peço que verifiquem seus PRs e nos deem feedback sobre este processo 👊😉. Estamos cientes de que alguns PRs são mais complexos, pois envolvem contribuições que vão além da simples adição de um perfil na pasta `community`. Para esses casos, pedimos um pouco de paciência. Faremos o nosso melhor para avaliar todos - sinta-se à vontade para nos marcar e manteremos o diálogo aberto.

Em tempo, gostaria de agradecer novamente à @elidianaandrade pelo trabalho excepcional com esta inicitiva. Você é incrível Eli 🚀🚀🚀

**Comment by elidianaandrade** [comment]
Obrigada, @falvojr! O trabalho de vocês foi essencial para dar um gás nesse projeto 🤩👏👏

**Comment by playerLuiz** [comment]
Amei o conteúdo da aula a professora explicou muito bem! uma coisa que acabei encontrando no caminho é que se você atualmente usar o "git log" o terminal começa a carregar infinitamente os arquivos dos community (que atualmente se encontra com +de 5 mil arquivos) acabou dando uma pane no meu terminal 😂😂.

Fica de aviso para quem for usar ele futuramente

**Comment by AnaBMamprin** [comment]
Enviei um README mas o arquivo foi o errado, foi um que só tinha um "esqueleto" escrito. O que está pronto, completo, está aqui mas não consigo enviar...

**Comment by JhonFXA** [comment]
@AnaBMamprin , tenta usar "git pull" antes de usar o push, talvez funcione

**Comment by AnaBMamprin** [comment]
> @AnaBMamprin , tenta usar "git pull" antes de usar o push, talvez funcione

Tá dando a mesma coisa ainda :(
![image](https://github.com/digitalinnovationone/dio-lab-open-source/assets/98192491/b3cd9b93-a4c9-48d0-88f2-a9f236cc6de4)

**Comment by falvojr** [comment]
> > @AnaBMamprin , tenta usar "git pull" antes de usar o push, talvez funcione
> 
> Tá dando a mesma coisa ainda :( 
> Não consigo avançar no curso por conta disso, tô muito chateada.

O erro que você está vendo indica que a sua branch local está desatualizada em relação à branch remota. Isso geralmente acontece quando há mudanças no repositório remoto que você ainda não tem localmente. Mesmo que você tenha tentado executar o git pull na `main` e recebido a mensagem "Already up to date.", isso não significa necessariamente que sua branch `feat/community/AnaBMamprin` está em sincronia com ela mesma remotamente... Entende? Por isso, acredito que a sua branch específica está desincronizada. Para verificar, faça o senguinte:

`git pull origin feat/community/AnaBMamprin`

Provavelmente esse comando evidenciará os conflitos, aí é só revolvê-los localmente e depois commitar e enviar suas alterações 😊 Confere se isso vai funcionar, por favor. Se consegue da um feedback por aqui, senão pode me marcar no seu repositório que analisarmos juntos por lá, ok?

**Comment by camiladanielledev** [comment]
Bom dia pessoal, tudo bem?
Fiquei com uma dúvida aqui, se alguém puder me ajudar, ficarei grata!
**Tem como fazer um pull request pelo Git bash?** Ou sempre tem que fazer pelo git hub mesmo?

**Comment by AnaBMamprin** [comment]
Boa noite!
Desculpe a demora, a faculdade e alguns problemas familiares estão tomando
muito do meu tempo e mente.
Usei o comando e apareceu o seguinte
[image: image.png]
Agora não sei como proceder...

Em sex., 3 de nov. de 2023 às 12:09, Venilton FalvoJr <
***@***.***> escreveu:

**Comment by leticiaveigacs** [comment]
Boa noite.

Gostaria pedir ajuda. Tenho problema com o Pull Request, continua dando erro mesmo com o nome do README é igual do meu usuário.

leticiaveica.md


![Captura de ecrã 2023-12-05 034908](https://github.com/digitalinnovationone/dio-lab-open-source/assets/125386281/c43d129e-6e63-4a4d-b040-bbd75b5f2af2)

**Comment by falvojr** [comment]
Oi pessoal, tudo bem?
Como o objetivo desta Issue foi explicar sobre a publicação dos Desafios de Projeto (Lab) na plataforma da DIO e solicitação de Pull Requests (PRs), acredito que com a automação que evidenciamos aqui https://github.com/digitalinnovationone/dio-lab-open-source/issues/5587#issuecomment-1763604239 o problema relacionado ao feedback dos PRs foi superado 🙏

Adicionalmente, gravei um vídeo complementar ao conteúdo do Lab da @elidianaandrade onde reforçei (pois a Eli já havia detalhado) toda a dinâmica de abertura e análise de PRs, ok? Na nossa plataforma, vocês podem acessar através do 
**Lab _Contribuindo em um Projeto Open Source no GitHub_, aula [_Resumão e Explicação Sobre a Automação dos PRs_](https://web.dio.me/project/desafio-de-projeto-contribuindo-em-um-projeto-open-source-no-github/learning/32153d6a-91fe-42d0-9b18-0d2be2e35197)** 👊😊

Sendo assim, irei fechar essa Issue, pois seu objetivo foi cumprido 🤗 

---
Em tempo, gostaria apenas de dar um direcionamento para algumas dúvidas que acabaram ficando em aberto por aqui:

- @AnaBMamprin, me desculpe pela demora para respondê-la, mas estas últimas semanas foram uma loucura por aqui. 🥲 Sobre seu último comentário, acredito que a imagem não foi enviada (ao menos pelo GitHub, não consigo vê-la). Se puder, bora continuar essa conversa lá no seu repositório? Dei um oi nesse commit por lá https://github.com/AnaBMamprin/dio-lab-open-source/commit/225d88506b1e867b8d819dc5ca4e81081d9e435f
- @camiladanielledev, é possível fazer pelo Git Bash sim, mas é um pouco mais complicado ([git-request-pull - Generates a summary of pending changes](https://git-scm.com/docs/git-request-pull)). Por isso, no contexto deste Lab recomendamos que façam pelo GitHub, visando simplificar este processo para uma familiarização gradual com o Git 🚀
- @leticiaveigacs dei uma olhadinha no seu PR e ele não está sendo aprovado porque existe mais de um arquivo modificado, dá uma olhadinha neste comentário que fiz lá https://github.com/digitalinnovationone/dio-lab-open-source/pull/18660#issuecomment-1840814522 😉

**Comment by Black-Simon45** [comment]
Não consegui fazer pelo terminal deu o erro de PR, depois que eu fiz como Falvo fez pelo GitHub aí percebi o erro de conflito devido o nome do arquivo que era pra ser igual ao do usuário. Mas muito interessante esse desafio, eu gostei muito, valeu pela revisão. 

![dio](https://github.com/digitalinnovationone/dio-lab-open-source/assets/150971708/b154720f-5e46-4deb-81db-43a7e019ac7d)

**Comment by FilipeOlliveira** [comment]
Olá! Alguém sabe o que significa isso (esse Warning)? Apareceu já ao usar o primeiro comando git clone, tanto com https quanto com o ssh. Está diferente do da Eli no vídeo. A pasta foi copiada, mas foi como se tivesse vindo arquivos a mais de outros. Por que aconteceu isso?

![Captura de tela 2024-01-08 183026](https://github.com/digitalinnovationone/dio-lab-open-source/assets/92556197/33a0ec4f-97c1-4f68-9c36-7510da9ed379)

**Comment by falvojr** [comment]
> Olá! Alguém sabe o que significa isso (esse Warning)? Apareceu já ao usar o primeiro comando git clone, tanto com https quanto com o ssh. Está diferente do da Eli no vídeo. A pasta foi copiada, mas foi como se tivesse vindo arquivos a mais de outros. Por que aconteceu isso?
> 
> ![Captura de tela 2024-01-08 183026](https://private-user-images.githubusercontent.com/92556197/295042697-33a0ec4f-97c1-4f68-9c36-7510da9ed379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTgzNzUsIm5iZiI6MTcwNDk5ODA3NSwicGF0aCI6Ii85MjU1NjE5Ny8yOTUwNDI2OTctMzNhMGVjNGYtOTdjMS00ZjY4LTljMzYtNzUxMGRhOWVkMzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE4MzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZDM2MWNmYWEyNjFlODY5MDFhY2I0Y2IxNGMxMDYzOTYwNWIwZjhhNjhkOWQ2NTI1Njc4NDFlZjg4YmMyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J7wUNHfLnpdlu0kAlzRGyp3LsaSwtf55EjNpL3nnEWU)

O aviso significa que alguns arquivos podem ter o mesmo nome se você não considerar as letras maiúsculas e minúsculas, o que pode causar confusão em sistemas como o Windows, que tratam 'Foto.jpg' e 'foto.jpg' como se fossem o mesmo arquivo. Entretanto, como você não vai modificar esses arquivos, isso não deve ser um problema para a abertura do seu PR 👊😉

**Comment by GustavoPereira-Dev** [comment]
> professora! preciso de ajuda! sempre que tento clonar no bash o repositório aparece essa mensagem: remote: Repository not found.
> fatal: repository 'https://github.com/clone/dio-lab-open-source.git/' not found
> 
> já pesquisei porem não consigo solucionar o problema...
> 

Bem, sobre isso aí pelo que percebi é o endereço que a url que seu remote  (https://github.com/clone/dio-lab-open-source.git) está indicando está incorreto
O certo era ter o seu nome de usuario (caso deseje clonar isso do fork criado por você) ao invés de "clone"
Resumidamente, é só você corrigir esse pequeno erro

**Comment by lszlsvgcon** [comment]
Bom projeto.

**Comment by GabrielHidaN** [comment]
Nice

**Comment by robertmenezesdev** [comment]
Top!!

**Comment by Hikaruyamanaka** [comment]
Me ajudou muito!

**Comment by georgefragoso1977** [comment]
> Não consegui fazer pelo terminal deu o erro de PR, depois que eu fiz como Falvo fez pelo GitHub aí percebi o erro de conflito devido o nome do arquivo que era pra ser igual ao do usuário. Mas muito interessante esse desafio, eu gostei muito, valeu pela revisão.
> 
> ![dio](https://private-user-images.githubusercontent.com/150971708/293107201-b154720f-5e46-4deb-81db-43a7e019ac7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTM3MjYsIm5iZiI6MTcxMzE1MzQyNiwicGF0aCI6Ii8xNTA5NzE3MDgvMjkzMTA3MjAxLWIxNTQ3MjBmLTVlNDYtNGRlYi04MWRiLTQzYTdlMDE5YWM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMzU3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjM4OTdiYTA2Mjc3MTAwNjAyZjAzNTE5NDdiYWIyNzU0MTkyNjhjYWI3YzU0ZGMwZDhhMmIzYzY1YjVjODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nX5m0vC1X6ru4-tf26bJ3Zi8nh2ZcD8wnJ7xW_AJ4og)



> Não consegui fazer pelo terminal deu o erro de PR, depois que eu fiz como Falvo fez pelo GitHub aí percebi o erro de conflito devido o nome do arquivo que era pra ser igual ao do usuário. Mas muito interessante esse desafio, eu gostei muito, valeu pela revisão.
> 
> ![dio](https://private-user-images.githubusercontent.com/150971708/293107201-b154720f-5e46-4deb-81db-43a7e019ac7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTM3MjYsIm5iZiI6MTcxMzE1MzQyNiwicGF0aCI6Ii8xNTA5NzE3MDgvMjkzMTA3MjAxLWIxNTQ3MjBmLTVlNDYtNGRlYi04MWRiLTQzYTdlMDE5YWM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMzU3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjM4OTdiYTA2Mjc3MTAwNjAyZjAzNTE5NDdiYWIyNzU0MTkyNjhjYWI3YzU0ZGMwZDhhMmIzYzY1YjVjODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nX5m0vC1X6ru4-tf26bJ3Zi8nh2ZcD8wnJ7xW_AJ4og)

@Black-Simon45 esse erro que você postou, mostra erro de acesso negado. Isso acontece pois você copiou a URL do repositório original, que realmente não se tem acesso para push. Observe que na URL aparece digitalinnovationone/... e deveria ser seu usuário/...

**Comment by georgefragoso1977** [comment]
Prezados, uma duvida. No meu PR ficou com mais de um arquivo modificado e vários commit. Logo pergunto:
1- Como resolver esta questão de haver mais de um arquivo modificado num PR? 
2 - Tem como alterar um PR já enviado? 
3 - Como desfazer commit, antes de um push?

**Comment by glaucopifi** [comment]
Cada dia fico mais fascinado com o Python, estou estudando justamente exemplo de classes então copiei para meu estudo o script, consegui fazer um projetinho de uma calculadora básica  usando as classes.

**Comment by Dev-Gabriel-Martins** [comment]
@falvojr @elidianaandrade No desafio do projeto, precisa ser exatamente isso o que tenho que entregar, ou posso enviar contribuição em outro projeto open-source. Ou criar um projeto open-source com colegas do Bootcamp e entregar ?

**Comment by viniciusdantasdc** [comment]
> professora! preciso de ajuda! sempre que tento clonar no bash o repositório aparece essa mensagem: remote: Repository not found. fatal: repository 'https://github.com/clone/dio-lab-open-source.git/' not found
> 
> já pesquisei porem não consigo solucionar o problema...

** Cuidado ao copiar e colar `Crrl+c` e depois executar o `paste` do botão direito, isso acaba add outros caracteres como "~" ao fim da url que o invalida.

**Comment by elidianaandrade** [comment]
Olá, @Dev-Gabriel-Martins! Sim, você pode enviar uma contribuição que fez em outro projeto Open Source 😁
Sobre criar um com colegas do Bootcamp, você pode aproveitar a categoria [Projetos Open Source](https://github.com/digitalinnovationone/dio-lab-open-source/discussions/categories/projetos-open-source) para compartilhar o projeto com a comunidade 😊🎉

**Comment by agamenonteccent** [comment]
Ótimo esta atividade. Para nossos conhecimentos na comunidade.

**Comment by akyrasouza** [comment]
Além do Profile README, podemos criar uma pasta em utils e colocar um arquivo markdown com algumas sugestões?

**Comment by welielton** [comment]
Eu estava igual um homem pré-histórico tentando corrigir o erro. Depois que fiz tudo de errado e consegui corrigir, foi que vi o vídeo seguinte mostrando como resolver 🤡🤡

**Comment by dmm76** [comment]
tive medo a principio dessa tarefa, parei um bom tempo meu bootcamp, nao conseguia entender direito o que fazer, retornei deppis de um bom tempo e completei, agora com mais segurança sobre utilizacao do github. Doeu mas o remédio funcionou

**Comment by SergioDevSousa** [comment]
o erro que tive foi uma configuração com minha branch main e master. obtive ajuda e entendi o porque. Estava usando o vscode no windows e quando instalei o wsl dava erro no commit. o nome do arquivo era igual ao usuário, tinha colocado com camellcase e sem e vi que o wsl trabalha com branch master. erro corrigido, trabalho entregue. Valeu

**Comment by FrancisBFTC** [comment]
Olá @elidianaandrade e @falvojr, adorei demais este curso e incentiva muito a comunidade contribuir com projetos no Github. Já fiz minha contribuição de perfil na Pull Request e também acabei de criar uma Issue baseada em uma sugestão de uma nova ideia para este repositório. Spoiler: **Novos projetos de software dentro deste mesmo repo pra galera perder o medo de contribuir com codificação.** Dê uma olhada lá e vejam se é algo viável.

**Comment by sallys03** [comment]
não consigo clonar na minha maquina . aparece Receiving objects:   0% (1/226655)
e fica só nisso, já tentei varias vezes

**Comment by gisengsoft** [comment]
> professora! preciso de ajuda! sempre que tento clonar no bash o repositório aparece essa mensagem: remote: Repository not found. fatal: repository 'https://github.com/clone/dio-lab-open-source.git/' not found
> 
> já pesquisei porem não consigo solucionar o problema...

Aqui tambem, desisti, mas também é muito grande pra ocupar espaço no meu hd.

**Comment by geodias-infraclound** [comment]
Olá, bom dia!
Muito obrigado Eli e Flavorjr por toda a explicação. É a primeira vez que estou trabalhando com Git e GitHub — no começo me senti bem perdido para conseguir entregar o projeto, mas com a ajuda de vocês e explorando a plataforma, percebi que não é tão difícil assim.
Vou seguir com o curso completo aqui na DIO para continuar evoluindo. Estou muito grato pela oportunidade de participar deste bootcamp e poder aprimorar minhas habilidades com Linux.

Valeu demais! 🚀💻

**Comment by douglasfariasil** [comment]
Ótima atividade, estou corrigindo erro.
